### ISSUE TITLE
install bitcoin 0.16.0

### ISSUE THREAD

**Issue by SierraLima** [Stadicus/guides#106]
this command doesn't install bitcoind

$ sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin-0.16.0/bin/*

I download and extract all the file but it doesn't work

best regards

**Comment by TheCHGoon** [comment]
did you get 16.1?

$ wget https://bitcoin.org/bin/bitcoin-core-0.16.1/bitcoin-0.16.1-arm-linux-gnueabihf.tar.gz

then:

$ sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin-0.16.1/bin/*

**Comment by Stadicus** [comment]
Could be the wrong binary for your platform. Do you use a Raspberry Pi? Did you download the ...arm-linux... file?

**Comment by SierraLima** [comment]
Raspberry Pi and downloaded the arm linux file

**Comment by Stadicus** [comment]
Might be file system corruption... Here are a few suggetions. Safe bet is to reflash the SD card and start from scratch, however.
https://raspberrypi.stackexchange.com/questions/5404/segmentation-fault

**Comment by Stadicus** [comment]
Maybe same issue here? What Raspberry Pi do you use exactly?
https://github.com/Stadicus/guides/issues/115

**Comment by SierraLima** [comment]
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

armv6l

CPU revision	: 7

**Comment by SierraLima** [comment]
raspberry PI Model B+

**Comment by Stadicus** [comment]
So I guess it's a Raspberry Pi 1 B+, right? This would unfortunately mean that it's not powerful enough, and there are no precompiled binaries available for this older (and totally different) cpu platform. See issue https://github.com/Stadicus/guides/issues/115

This guide needs at least a Pi2, I suggest to get the latest P3.

**Comment by SierraLima** [comment]
Raspberry pi 3 B+

**Comment by SierraLima** [comment]
I reflashed the SD card and started again from scratch but still the same problem

**Comment by Stadicus** [comment]
Can you post the output of `cat /proc/cpuinfo`, please?

**Comment by SierraLima** [comment]
Raspberry Pi Model B Plus Rev 1.2

processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 900032
Serial		: 0000000080b1ff9b

**Comment by SierraLima** [comment]
Thanks so much I interchanged my two raspberry

**Comment by Stadicus** [comment]
I had a hunch... 👍
