### ISSUE TITLE
Segmentation Fault after bitcoind --version

### ISSUE THREAD

**Issue by theDavidCoen** [Stadicus/guides#115]
Hi,
I'm following the guide and I have just installed the 0.16.1 bitcoin version. Now I have to check the version with the command bitcoind --version but I obtain the message "Segmentation fault".
My SD is brand new, my raspberry Pi 1 is powered by a phone charger and my external hard drive has its own charger. 
Could you help me please?

**Comment by Stadicus** [comment]
I have not updated to bitcoind 0.16.1 yet. Just now, I downloaded the binary and checked it, it should work. As `admin` user:
```
$ cd ~/download
$ wget https://bitcoin.org/bin/bitcoin-core-0.16.1/bitcoin-0.16.1-arm-linux-gnueabihf.tar.gz
$ tar -xvf bitcoin-0.16.1-arm-linux-gnueabihf.tar.gz
$ bitcoin-0.16.1/bin/bitcoind --version
Bitcoin Core Daemon version v0.16.1
Copyright (C) 2009-2018 The Bitcoin Core developers
```

What exacty Pi are you using? Can you please post the output of the following commands?
```
$ cat /etc/os-release
$ uname -m
$ cat /proc/cpuinfo | grep revision
```

**Comment by theDavidCoen** [comment]
Should be a raspberry pi model B, in the pics you should see the specs.
Tomorrow I will send you the specs

Il mer 11 lug 2018, 18:47 Stadicus <notifications@github.com> ha scritto:

**Comment by Stadicus** [comment]
The question is: Raspberry Pi 1, 2 or 3, and model A / B / B+

**Comment by theDavidCoen** [comment]
Definitely raspberry pi 1 model B

Il 11 lug 2018 7:43 PM, "Stadicus" <notifications@github.com> ha scritto:

The question is: Raspberry Pi 1, 2 or 3, and model A / B / B+

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Stadicus/guides/issues/115#issuecomment-404253728>, or mute
the thread

**Comment by Stadicus** [comment]
The Pi 1 uses a different CPU than the newer Pies and I think it is not compatible with the precompiled Bitcoin Core binaries. 

The solution would be to compile it yourself from source. But I don't think this setup will work on a Pi 1, as it has only 1 core (512MB RAM), vs 4 core (1GB RAM) on a Raspberry Pi 2 or 3.

**Comment by theDavidCoen** [comment]
It's exactly what I thought. Unfortunately I'm not able to compile! I will
try with a raspberry pi 3 of a friend of mine and I will let you know.
Could you keep open this thread so I can eventually confirm your
hypothesis?
Thanks a lot!

Il mer 11 lug 2018, 19:53 Stadicus <notifications@github.com> ha scritto:

**Comment by Stadicus** [comment]
Will do, good luck! 👍

**Comment by theDavidCoen** [comment]
I can confirm that the problem is with Raspberry 1. I have now a PI 3 model B+ and I can install the bitcoin core

**Comment by Stadicus** [comment]
Very cool, have fun with your own full node! :-)

**Comment by Stadicus** [comment]
I guess this issue is resolved, correct?
