### ISSUE TITLE
mount can't find PARTUUID

### ISSUE THREAD

**Issue by rocky3xr** [Stadicus/guides#116]
![mount](https://user-images.githubusercontent.com/33218103/42589494-6d8bba14-8541-11e8-99ed-ec89207300e7.PNG)
I get this issue after formating the hdd, Does anyone know from where it comes?
![etc fstab](https://user-images.githubusercontent.com/33218103/42589652-ff10eb94-8541-11e8-9a13-221cf70da279.PNG)

**Comment by rocky3xr** [comment]
Okay, my problem was I typed "PARTUUID" instead of "UUID"

**Comment by Stadicus** [comment]
Didn't see it either at first glance... :-) Enjoy the rest of the guide!
