### ISSUE TITLE
Copied blocks crash bitcoind

### ISSUE THREAD

**Issue by nipponese** [Stadicus/guides#120]
I am moving to mainnet, but bitcoind always crashes on start up while trying to verify the blocks and chainstate copied from my other machine:

```
2018-07-11 21:06:03 Bitcoin Core version v0.16.1 (release build)
2018-07-11 21:06:03 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2018-07-11 21:06:03 Assuming ancestors of block 0000000000000000005214481d2d96f898e3d5416e43359c145944a909d242e0 have valid signatures.
...
2018-07-11 21:06:03 init message: Loading block index...
2018-07-11 21:06:03 Opening LevelDB in /home/bitcoin/.bitcoin/blocks/index
2018-07-11 21:06:04 Opened LevelDB successfully
2018-07-11 21:06:04 Using obfuscation key for /home/bitcoin/.bitcoin/blocks/index: 0000000000000000
```

If I remove the `blocks` and `chainstate` folder, bitcoind starts up without issue and starts downloading new blocks. 

Any ideas?

**Comment by Stadicus** [comment]
Hej @nipponese, not sure why this happens. Deleting the folders just makes the Pi download the whole blockchain again, that can take weeks...

Just to make sure, on **mainnet** you
* downloaded the **mainnet** blockchain (~200 GB) on a regular computer using Bitcoin Core with the option `txindex=1` in the `bitcoin.conf` and it is fully synced
* copied the whole Bitcoin data directory to your RaspiBolt using SCP 
* stopped all services, adjusted the configuration, started the services
* bitcoind is starting but then it crashes

Not sure if this could be a memory issue. What Raspberry Pi do you have? How is your external hard disk formatted? Is swap enabled? 

Can you post the output of the following commands, please?
```
uname -a
sudo df
sudo lsblk -o UUID,NAME,FSTYPE,SIZE,LABEL,MODEL
cat /proc/swaps 
grep -v '^#' /etc/dphys-swapfile | grep -v '^$'
```

**Comment by nipponese** [comment]
I think my config is ok. My swap file is 2gb.

I am loading mainnet `blocks` and `chainstate` from my Mac.  `txindex=1` is set.

The only difference between my process your manual is I used `rsync` to copy the files over instead of `scp`.

```
admin@machinename:~ $ cat /proc/device-tree/model
Raspberry Pi 3 Model B Rev 1.2

admin@machinename:~ $ uname -a
Linux machinename 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

admin@machinename:~ $ sudo df
Filesystem      1K-blocks      Used  Available Use% Mounted on
/dev/root        30612732  27559784    1776812  94% /
devtmpfs           470116         0     470116   0% /dev
tmpfs              474724         0     474724   0% /dev/shm
tmpfs              474724     18228     456496   4% /run
tmpfs                5120         4       5116   1% /run/lock
tmpfs              474724         0     474724   0% /sys/fs/cgroup
/dev/mmcblk0p1      43436     22138      21298  51% /boot
/dev/sda1      3844607992 253142912 3396099552   7% /mnt/hdd
tmpfs               94944         0      94944   0% /run/user/1000
admin@machinename:~ $ 
admin@machinename:~ $ sudo lsblk -o UUID,NAME,FSTYPE,SIZE,LABEL,MODEL
UUID                                 NAME        FSTYPE  SIZE LABEL  MODEL
                                     sda                 3.7T        My Passp
0dcafb17-4de0-468b-9174-7e5e02bb6ad2 └─sda1      ext4    3.7T        
                                     mmcblk0            29.7G        
A365-6756                            ├─mmcblk0p1 vfat   43.1M boot   
90a83158-560d-48ee-9de9-40c51d93c287 └─mmcblk0p2 ext4   29.7G rootfs 

admin@machinename:~ $ cat /proc/swaps 
Filename        Type    Size  Used  Priority
/mnt/hdd/swapfile                  file    2097148 29184 -2

admin@machinename:~ $ grep -v '^#' /etc/dphys-swapfile | grep -v '^$'
CONF_SWAPFILE=/mnt/hdd/swapfile
CONF_SWAPSIZE=2048
admin@machinename:~ $ 
```

**Comment by Stadicus** [comment]
Not really sure what could cause this. If it's working on your Mac, it should also work on the Pi, its the exact same codebase. 

Did you check permissions & ownership? The whole external hdd should be owned by "bitcoin", maybe that's an issue due to rsync?

**Comment by nipponese** [comment]
Yeah, it seems likely that using rsync was the culprit. After copying the files over using SFTP via Transmit, bitcoind read the index indexes without issue.
