### ISSUE TITLE
Issue when connecting to LN $ sudo journalctl -f -u lnd

### ISSUE THREAD

**Issue by rocky3xr** [Stadicus/guides#123]
![connecting](https://user-images.githubusercontent.com/33218103/42649326-b4045f14-8609-11e8-9a62-94fe7189e9b5.PNG)

**Comment by rocky3xr** [comment]
![rpc issue](https://user-images.githubusercontent.com/33218103/42650099-ca7cd184-860b-11e8-94a1-09c8ac908fe8.PNG)
I get this issie aswell, I think both are connected

**Comment by rocky3xr** [comment]
![newaddress](https://user-images.githubusercontent.com/33218103/42650301-576e37ae-860c-11e8-9a24-21cb74b8aa11.PNG)
When I try to get some btc test I get this issue, is it because I'm still updating the chain?

**Comment by Stadicus** [comment]
I think bitcoind might still by syncing. What does the following command return?
`$ sudo tail -f /home/bitcoin/.bitcoin/debug.log`

**Comment by rocky3xr** [comment]
![results conflict](https://user-images.githubusercontent.com/33218103/42654198-23357252-8618-11e8-90df-8eb7378682bb.PNG)
This is what I get when I type 
`$ sudo tail -f /home/bitcoin/.bitcoin/debug.log`

and

`$ sudo tail -f /home/bitcoin/.bitcoin/testnet3/debug.log`

**Comment by Stadicus** [comment]
Ah, you are on testnet. Can you copy the last 200 rows of the log into https://pastebin.com/ and post the link to your paste here? I need more than this one cut-off line to help.

As user "admin":
`sudo tail -n 200 /home/bitcoin/.bitcoin/testnet3/debug.log`

**Comment by rocky3xr** [comment]
Sure, here it is [pastebin 200 rows](https://pastebin.com/adheSrCJ)

**Comment by Stadicus** [comment]
Yes, looks good. It's at 69%, give it a few mir hours.

**Comment by rocky3xr** [comment]
![still the issue](https://user-images.githubusercontent.com/33218103/42675116-e1659df6-8672-11e8-94d5-0b27f8c5c607.PNG)
I´m fully synced to testnet, still rcp issue

**Comment by rocky3xr** [comment]
I solved the problem what is bold text is what I added

# RaspiBolt LND Mainnet: lnd configuration
# /home/bitcoin/.lnd/lnd.conf

[Application Options]
debuglevel=info
debughtlc=true
maxpendingchannels=5
alias=YOUR_NAME [LND]
color=#68F442

[Bitcoin]
bitcoin.active=1

# enable either testnet or mainnet
bitcoin.testnet=1
#bitcoin.mainnet=1

bitcoin.node=bitcoind

**[bitcoind]
bitcoind.rpcuser=raspibolt
bitcoind.rpcpass=MyPassword**

[autopilot]
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.6

**Comment by Stadicus** [comment]
Hej @rocky3xr, great, glad you solved it. This is usually not necessary, `lnd` reuses the information in the `bitcoin.conf` file if it can find it in the standard path (`.bitcoin` folder in the same user's home directory).

Maybe there's something different here, or it's a permission issue. Nonetheless, happy it works!
