### ISSUE TITLE
"ssid" and "password" on Pi wifi

### ISSUE THREAD

**Issue by aberratioictus** [Stadicus/guides#129]
Hello Stadicus, first of all: thank you very much for this guide. I am currently in the process of setting up my nodes and this just helps so much!

One thing i wanted to note is that on the section about connecting the Pi to wifi, the values for ssid and psk need to be in quotes. I am very new to using a Pi and just spent the last two hours figuring out what was going on.

Thank you again for this awesome guide!

**Comment by Stadicus** [comment]
Hej @aberratioictus , thanks for your feedback! I just fixed the guide: https://github.com/Stadicus/guides/commit/a21788c0518618d17093e3f447f68a53e4efa6e7

Have fun setting up your own full node & spread the word! ;-)
