### ISSUE TITLE
autopilot not working

### ISSUE THREAD

**Issue by cootpursuits** [Stadicus/guides#13]
Should the autopilot be working with the binaries used in the guide? It doesn't for me, I'm having this issue: https://github.com/lightninglabs/lightning-app/issues/26

**Comment by Stadicus** [comment]
Yes, it's working for me. Once everything is fully synced, LND starts opening channels one by one. I never compiled the beta, only using the binary.

**Comment by Stadicus** [comment]
Maybe connect to a few nodes to get network info? 

You can always disable autopilot in `lnd.conf`and create your channels manually.

**Comment by cootpursuits** [comment]
Interesting. I'm synced to the chain, the wallet has a confirmed balance, I manually connected to the nodes suggested in the other thread, and I'm seeing the peers, yet there are no channels opened.
