### ISSUE TITLE
Sending from Eclair to LND node takes >240 seconds

### ISSUE THREAD

**Issue by jrwagh333** [Stadicus/guides#145]
Opened a channel from Eclair to my own LND node

Channel is open and funded
Sending payment from Eclair to node takes around 5 minutes each time - With varying amounts of sat

Curious as to what the issue is
Have >25 connections in bitcoind

**Comment by Stadicus** [comment]
Hard to say, that's more of an Eclair topic than an issue with your RaspiBolt. Do you experience this also for other services like y'alls etc.?
