### ISSUE TITLE
Channel closed - how to view log

### ISSUE THREAD

**Issue by jrwagh333** [Stadicus/guides#147]
A channel was closed overnight and I wanted to view the log file of if it was requested and the amount that was in the channel.

I am unable to find the log file on lnd

**Comment by Stadicus** [comment]
The log files can be huge and there are several techniques to parse them for specific information. The simplest way is to use `grep` to list all lines that contain a certain text, like the pub-key of the node in question. But this can be any text really. Depending on your user, you might need `sudo` to access the file.

`$ grep 03012a23c769decc4fb40a92d5300692b576cb8dc887072580638b97911742554c /home/bitcoin/.lnd/logs/bitcoin/mainnet/lnd.log`

These logfiles are compressed regularly. To parse them directly, you can use `zgrep`.
```
bitcoin@RaspiBolt:~ $ ls /home/bitcoin/.lnd/logs/bitcoin/mainnet/
insgesamt 12104
drwx------ 2 bitcoin bitcoin    4096 Jul 22 04:00 .
drwx------ 4 bitcoin bitcoin    4096 Mär 18 03:42 ..
-rw-r--r-- 1 bitcoin bitcoin 8300142 Jul 24 07:33 lnd.log
-rw-r--r-- 1 bitcoin bitcoin 1355630 Jul 13 13:42 lnd.log.1672.gz
-rw-r--r-- 1 bitcoin bitcoin 1342216 Jul 17 02:53 lnd.log.1673.gz
-rw-r--r-- 1 bitcoin bitcoin 1378427 Jul 22 04:00 lnd.log.1674.gz

bitcoin@RaspiBolt:~ $ zgrep 03012a23c769decc4fb40a92d5300692b576cb8dc887072580638b97911742554c /home/bitcoin/.lnd/logs/bitcoin/mainnet/lnd.log.1672.gz
```
