### ISSUE TITLE
Something about LN is depleting memory

### ISSUE THREAD

**Issue by aberratioictus** [Stadicus/guides#156]
Hey everyone and @Stadicus,

I just switched back from mainnet to testnet to do some testing on the LN API. Switching off `autopilot`, creating channels, closing channels, etc.

Something about this immensly drains the Pi's available memory, rendering it almost unresponsive - in fact unresponsive for the last 10 minutes. Here is one of the last responses it gave to me on the `raspibolt` command:

![unbenannt](https://user-images.githubusercontent.com/41243369/43355735-bed38398-9261-11e8-92ac-d3b3b897156e.jpg)

**Comment by aberratioictus** [comment]
Nevermind. I think this just solved itself. After another 15 minutes the Pi finally started responding again. Still worries me what the issue was there and how to fix it until there is real money on the line in mainnet...

**Comment by Stadicus** [comment]
Hej @aberratioictus, such a spike is quite unusual, but not really a problem. LND sometimes takes a lot of memory, eg. when creating the wallet, that's why there's the swap file, to buffer that.
