### ISSUE TITLE
mainnet and testnet3 on one Bolt

### ISSUE THREAD

**Issue by k9ert** [Stadicus/guides#157]
Thank you very much for all your work. Really helpfull! I'm currently preparing for mainnet on the Thundroid and reviewing the ways to go:
https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_50_mainnet.md

I think (and hope) this approach can be improved. I would like to run bitcoind and lnd on mainnet and on testnet at the same time. 
For bitcoind, that was quite straightforward. Simply having two systemd-configurations did the trick. I decided to copy bitcoin.conf in the testnet3-folder. and then have two systemd-files.
The only thing which took some time was that i need to configure different ports for 
zmqpubrawblock and zmqpubrawtx. bitcoind could be a bit more helpful with logging here.

Now i would like to follow a similiar approach for lnd. My guess is that this is more difficult to do it similiar. 

Before i start messing around here, do you have any recommendations? Isn't that a reasonable improvement? Not sure how you plan collaboration on guides like this? How can one contribute?

Thanks

**Comment by Stadicus** [comment]
Thanks for your feedback! I've never run both services at the same time, might quickly becokme a ressource issue... But check out this writeup by @robclark56 (RaspiBolt Duo)
https://github.com/robclark56/RaspiBolt-Extras/blob/master/README.md

**Comment by k9ert** [comment]
Wow, great! Thanks, that's exactly what i'm searching for.
I've done a wrong title. Running both on a Thundroid should be fine, imho.
