### ISSUE TITLE
Unclear how to create wallet for mainnet

### ISSUE THREAD

**Issue by yzernik** [Stadicus/guides#159]
When I create the wallet for mainnet, the interactive prompt asks if I already have a cipher seed mnemonic.

It is not clear from the guide if the same cipher seed mnemonic and passphrase can be used as with the testnet wallet. Is it necessary to create a new mnemonic?

**Comment by Stadicus** [comment]
Both methods should work, but I never tried to reuse the mnemonic. I always set up a new cipher.
