### ISSUE TITLE
rpcport for testnet

### ISSUE THREAD

**Issue by woodyjon** [Stadicus/guides#163]
I might be wrong, but maybe the rpcport in bitcoin.conf file when working on testnet should be rpcport=18332 instead of 8332.
When trying to follow the guide and launching LND on the testnet, LND would exit after opening the wallet because of an RPC connection. But after changing rpcport in bitcoin.conf to 18332, LND started successfully.

**Comment by Stadicus** [comment]
Thanks, bad update. Fixed.

**Comment by woodyjon** [comment]
Thanks for your guide. It's awesome. Just sent a coffee your way on y'alls to confirm that I successfully installed everything.
