### ISSUE TITLE
linksys wrt1900acs started to crash

### ISSUE THREAD

**Issue by 3ntranced** [Stadicus/guides#164]
Hey, have you had any issues with your routers? I have a feeling my wrt1900acs is inaccessible at times and laggy because somehow it gets overloaded by connections to pi running lnd and bitcoin core. Do you think thats possible? Right now, pi is off, and this is the log I am getting on the router:

Incoming log
--

144.217.71.143 |   | 18333 |  
185.217.243.40 |   | 18333 |  
144.217.71.143 |   | 18333 |  
185.217.243.40 |   | 18333 |  
197.245.46.172 |   | 18333 |  
144.217.71.143 |   | 18333 |  
197.245.46.172 |   | 18333 |  
144.217.71.143 |   | 18333 |  
197.245.46.172 |   | 18333 |  
144.217.71.143 |   | 18333 |  
197.245.46.172 |   | 18333 |  
144.217.71.143 |   | 18333 |  
197.245.46.172 |   | 18333 |  
188.65.213.21 |   | 8333 |  
197.245.46.172 |   | 18333 |  
85.216.75.225 |   | 9735 |  
197.245.46.172 |   | 18333 |  
188.65.213.21 |   | 8333 |  
197.245.46.172 |   | 18333 |  
144.217.71.143 |   | 18333 |  
188.65.213.21 |   | 8333 |  
197.245.46.172 |   | 18333 |  
188.65.213.21 |   | 8333 |  
197.245.46.172 |   | 18333 |  
188.65.213.21 |   | 8333 |  
144.217.71.143 |   | 18333 |  
197.245.46.172 |   | 18333 |  
144.217.71.143 |   | 18333 |  
197.245.46.172 |   | 18333 |  
144.217.71.143 |   | 18333 |  
60.190.54.122 |   | 18333 |  
144.217.71.143 |   | 18333 |  
35.166.249.115 |   | 8333 |  
144.217.71.143 |   | 18333 |  
35.166.249.115 |   | 8333 |  
144.217.71.143 |   | 18333 |  
35.166.249.115 |   | 8333 |  
197.245.46.172 |   | 18333

**Comment by Stadicus** [comment]
These are connection attempts to your Bitcoin node, but that's perfectly normal. A home use router is able to handle tons of connections and just hands them to the target. It should not lag because of these, especially not a wrt1900acs. Anyway, hard to say without timestamps.

I use an ASUS router and handle multiple servers and nodes, including lightning (very heavy gossip!) and never had any issues.
