### ISSUE TITLE
LCD touchscreen compatible ?

### ISSUE THREAD

**Issue by becrypto** [Stadicus/guides#167]
Hi

LCD touchscreen compatible with raspy bolt ?
if not, possible integrate that pls ?

thx a lot

**Comment by Stadicus** [comment]
This is a generic Raspberry Pi topic. The node is compatible to a various range of LCD screens, I personally use the PiScreen (3.5", 480x320, based on XPT2046) that is available everywhere for ~$12, as explained here:
http://ozzmaker.com/piscreen-driver-install-instructions-2/

I have not dabbled with the touch functionality yet.
