### ISSUE TITLE
BUILD FAILED --> Bitcoin download checksum not OK

### ISSUE THREAD

**Issue by Smiggel** [Stadicus/guides#175]
Trying to setup a node the manual way. Installing using the script works fine until it should check the code of Bitcoin and it stops with the error "BUILD FAILED --> Bitcoin download checksum not OK". 

Anyone else having this issue?

**Comment by Stadicus** [comment]
Did you figure out what the issue was?

**Comment by Smiggel** [comment]
Yes. I stripped down Raspbian to undo it from software I would not need. Guess I stripped too much which resulted in the problem. A new install without too much stripping worked. :-)
