### ISSUE TITLE
Raspibolt output on LCD?

### ISSUE THREAD

**Issue by Smiggel** [Stadicus/guides#183]
Hi,

I would like to see the output of the Raspibolt function to be able to be displayed on an attached LCD so you can read the status from there. Would this be possible?

I have seen something in the docs of RaspiBlitz, but have no idea how to do that with this setup.

**Comment by Stadicus** [comment]
Yes, it's definitely possible, it involves the following steps:

* connecting and configuring the display
* configuring a dedicated user without privileges (eg. "displayuser") and setting this user to autologin
* giving the user access rights (read only) to the bitcoin & lightning status info
* running the info script on startup and refreshing it constantly.

This is outside of the scope for this guide, but as you mentioned, the RaspiBlitz has a working implementation you can peek at:
https://github.com/rootzoll/raspiblitz

**Comment by Smiggel** [comment]
@Stadicus This was more meant as a bonus feature like the other bonuses.

**Comment by Stadicus** [comment]
Feel free to create a pull request. 😉
