### ISSUE TITLE
Auto unlock timeout

### ISSUE THREAD

**Issue by irekzielinski** [Stadicus/guides#191]
Had issues with auto-unlock script timing out:

`admin@odroid:~$ sudo systemctl restart lnd
Job for lnd.service failed because a timeout was exceeded.`

I believe the cause is that the unlock script waits for 180s:
/bin/sleep 180s

But the whole service start time out is also set to 180s in /etc/systemd/system/lnd.service
TimeoutSec=180

increasing this value to let's say 240 seems to make the script much more reliable.

**Comment by Stadicus** [comment]
Thanks, that's an oversight on my part. I adjusted the guide.
