### ISSUE TITLE
Speed up unlock script

### ISSUE THREAD

**Issue by irekzielinski** [Stadicus/guides#197]
Unlock script when added to LND configuration - makes each restart of LND service very slow (3 minutes).
I understand that this 3 minute wait is really important on boot of the system, when we want to make sure bitcoind is up and running, etc. Subsequent restarts of lnd don't really need 3 minutes timeout.

I modified my unlock script to do 3 minute wait only if system was booted recently (less than 5 minutes ago), otherwise wait for 30 seconds only (to allow for lnd to start before calling for unlock).

```
upSeconds="$(cat /proc/uptime | grep -o '^[0-9]\+')"
upMins=$((${upSeconds} / 60))

if [ "${upMins}" -lt "5" ]
then
    /bin/sleep 180s
else
    /bin/sleep 30s
fi
```

**Comment by Stadicus** [comment]
Great addition, thanks! Will include in next iteration.

**Comment by Stadicus** [comment]
https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_6A_auto-unlock.md
