### ISSUE TITLE
lnd error state: min relay fee not met

### ISSUE THREAD

**Issue by ZebulonFrantzich** [Stadicus/guides#208]
After updating to lnd v0.5-beta, I ran into the following error: `min relay fee not met`

I ran into the error within a minute of running `lncli unlock`. The issue is patched in the latest version of lnd, but there might be a few pre-signed transactions from the previous un-patched lnd version. (https://github.com/lightningnetwork/lnd/issues/1912)

The solution that worked for me is described in the reference link above:
Edit `/home/bitcoin/.bitcoin/bitcoin.conf`
Add `minrelaytxfee=0`
Save and restart bitcoind and lnd.

@Stadicus Just wanted to let you know I ran into this issue in case others ask.

**Comment by Stadicus** [comment]
I'll leave it open for now, as a reference for others.
