### ISSUE TITLE
OpenVPN on RPi3 question

### ISSUE THREAD

**Issue by dawiepoolman** [Stadicus/guides#215]
Hi guys

Silly question, would it not be possible (arguably even recommended) to run one's node behind a VPN?
I see there are instructions to load OpenVPN on a RPi:
http://www.ibvpn.com/billing/knowledgebase/133/OpenVPN-configuration-for-Raspberry-PI.html

I take one's uri requires a static IP which seems possible to configure a static IP on OpenVPN as well e.g. as mentioned in another walkthroug:
https://www.1and1.com/digitalguide/server/configuration/vpn-server-set-up-via-raspberry-pi-and-openvpn/

Thoughts? Pros/cons/complexities?

**Comment by Stadicus** [comment]
I thought about that and it's certainly possible. You would need either 
* a fixed ip from VPN provider, however, which is not cheap, or
* run your own OpenVPN server (probably on a cloud machine), also not that cheap and more complex

I think the configuration of a ynamic DNS update, giving you your own subdomain that always points to your IP address is much easier. Some router have this built in, other can update public services and some, like https://freedns.afraid.org, are very easy to regularly update with a linux script.

Lightning is still operating on IP level, but I hope UPnP / NAT traversal will get better. Meanwhile, people can still connect to your node using the sub-domain name.

Or simply use Tor, which also gives you a fixed onion address.

**Comment by Stadicus** [comment]
Closing for now, feel free to reopen with additional input
