### ISSUE TITLE
New macaroons won't create before you unlock/create a wallet.

### ISSUE THREAD

**Issue by CodingMuziekwijk** [Stadicus/guides#226]
It might be worth mentioning in the LND update that the new macaroons won't be created if you don't unlock the wallet first. Something like this would probably be enough:

> $ sudo nano /home/bitcoin/.bitcoin/bitcoin.conf`  
> zmqpubrawblock=tcp://127.0.0.1:28332
> zmqpubrawtx=tcp://127.0.0.1:28333
> 
> $ sudo systemctl restart bitcoind
> $ sudo systemctl restart lnd

- Unlock the wallet (to create the new macaroons)
> $ lncli unlock

**Comment by Stadicus** [comment]
Thanks for pointing that out. When I upgraded, I thought the macaroons were created on service restart, I adjusted the guide.
