### ISSUE TITLE
Lightning web interface: Can't start server

### ISSUE THREAD

**Issue by Sowiedu** [Stadicus/guides#239]
When starting the server, first it says macaroons enabled, then some hashes, then the following:

info:    App listening on 0.0.0.0 port 8280
(node:1350) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
warn:    tail data timeout, killing process 1363

Nothing after that.

**Comment by Stadicus** [comment]
I had to remove the web interface from this guide, it's no longer maintained and I cannot really support in solving issues regarding this project. 

Feel fee to test the "Ride the Lightning" interface that is actively being built and tested on the RaspiBolt (although not by me): https://github.com/ShahanaFarooqui/RTL/blob/master/README.md
