### ISSUE TITLE
EXT-4-fs error

### ISSUE THREAD

**Issue by Qurt99** [Stadicus/guides#253]
I'm stuck trying to get testnet blockchain to download. I'm monitoring the log file and it syncs for a few minutes and then all of a sudden it stops. When I run `dmesg` last few lines are these:

```
[  996.783110] EXT4-fs error (device sda): ext4_find_entry:1437: inode #12582913: comm bitcoind: reading directory lblock 0
[  996.787906] EXT4-fs error (device sda): ext4_find_entry:1437: inode #12582913: comm bitcoin-shutoff: reading directory lblock 0
[  996.792374] EXT4-fs error (device sda): ext4_find_entry:1437: inode #12582913: comm bitcoin-shutoff: reading directory lblock 0
```
I tried fixing the filesystem with `fsck` and doing everything from scratch. While `fsck` did seem to fix some unrelated errors, the situation did not change. I'm running Pi 3 with 3.5" internal hard drive, SATA to USB adapter and external power supply for the hard drive. I'm pretty sure the hard drive is healthy as it was recently tested for bad sectors. Any idea what could be causing this error?

**Comment by Stadicus** [comment]
Never had any issues related to ext4. Can you try with a different hard disk?
