### ISSUE TITLE
Downloading Bitcoin Core

### ISSUE THREAD

**Issue by BitcoinVegan** [Stadicus/guides#258]
Hello Stadicus, hope all is well. I have run across an issue. I'm trying to download bitcoin core to my external hard drive but it keeps going to my computer and it's says low disk space, but I'm sending it to my external can you assist me with this?

**Comment by Stadicus** [comment]
Hi @BitcoinVegan, can you please provide additional info?
* operating system
* drive letter / size of your external hard disk

Please check, what data directory is configured for Bitcoin. My guess is that it points to your internal hdd.
https://en.bitcoin.it/wiki/Data_directory
