### ISSUE TITLE
Checking lnd version error

### ISSUE THREAD

**Issue by bckbmath** [Stadicus/guides#266]
When I do:

```
$ lnd --version
Segmentation fault
```

What does this mean?

**Comment by Stadicus** [comment]
You probably downloaded the wrong version for your CPU architecture.

* Do you use a Raspberry Pi 3? --> LND ARMv7 is needed
* Raspberry Pi (1) or Zero, or a different model?

**Comment by bckbmath** [comment]
its an rpi 3 and i downloaded lnd-linux-armv7-v0.5-beta

**Comment by bckbmath** [comment]
lnd --version
lnd version 0.5.0-beta commit=

lnd 0.5.1 beta rc1 solves the problem
