### ISSUE TITLE
macaroon issue when upgrading to lnd 0.5 beta for Litecoin

### ISSUE THREAD

**Issue by gbwx-net** [Stadicus/guides#268]
While changing all references to bitcoin and bitcoind to litecoin and litecoind has worked well for this tute. The upgrade to lnd 0.5-beta poses a perculiar issue. It seems lnd must have a chain path hardcoded now as with lnd on bitcoind it looks for macaroons at

/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon 

So in theory changing to litecoin user and mainnet it should look in 

/home/litecoin/.lnd/data/chain/litecoin/mainnet/admin.macaroon 

However this is not the case for lnd 0.5-beta, it does not grab the chain name from the conf, it wants the macaroon at

/home/litecoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon 

and subsequently

/home/admin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon 

Simple fix is to create both (litecoin and admin users) bitcoin/mainnet/ folders and symlink admin.macaroon

**Comment by Stadicus** [comment]
Nice find, thanks for explaining. Nothing much I can do with my guide, but reporting that to LND directly would definitely help.
