### ISSUE TITLE
Updating packages - PAM configuration locally modified

### ISSUE THREAD

**Issue by IvanThinking** [Stadicus/guides#279]
I'm doing a basic sudo apt-get update | sudo apt upgrade and I get the following screen:

One or more of the files                                                  
 /etc/pam.d/common-{auth,account,password,session} have been locally       
modified.  Please indicate whether these local changes should be          
overridden using the system-provided configuration.  If you decline this  
option, you will need to manage your system's authentication              
configuration by hand.                                                    
                                                                          
Override local changes to /etc/pam.d/common-*? 

___
What is the appropriate response to this?

**Comment by Stadicus** [comment]
Does not really matter. Keep them or override to defaul again and redo the changes highlighted here:
https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_20_pi.md#increase-your-open-files-limit
