### ISSUE TITLE
Download and verify Bitcoin Core: Link to release signatures

### ISSUE THREAD

**Issue by jguchte** [Stadicus/guides#290]
guides/raspibolt/raspibolt_10_preparations.md

The hyperlink in "Compare this value with the release signatures. For the Windows v0.17.0.1 setup binaries.." points to the release signatures of Bitcoin Core 0.16.3. 

https://bitcoin.org/bin/bitcoin-core-0.16.3/SHA256SUMS.asc

Instead of the release signatures of Bitcoin Core 0.17.0.1.
https://bitcoin.org/bin/bitcoin-core-0.17.0.1/SHA256SUMS.asc

**Comment by Stadicus** [comment]
Thanks, fixed!
