### ISSUE TITLE
Part 3

### ISSUE THREAD

**Issue by Kartereo** [Stadicus/guides#295]
When can we expect part 3? I am definitely excited to get front ends added ;-) I am new here and this is the only way I know how to ask questions.

**Comment by Stadicus** [comment]
I'm currently working on an update to the Thundroid guide, as there have been some major changes. After that I'll work on the part 3, I'd say February / March? 

Feel free to poke around in the RaspiBolt section. Most stuff has already been documented for Raspberry Pi and should work with minor tweaks on your Odroid.
