### ISSUE TITLE
Cannot ssh to raspberry pi anymore

### ISSUE THREAD

**Issue by dlawant** [Stadicus/guides#299]
Hey everyone, sorry for such a noobie question. My node works on BTC and LND (testnet), but now I cannot ssh into my raspberry pi anymore. I get the following message: "Permission denied (publickey)."

I had ssh keys configured and was logging in perfectly to the pi. I got into the pi with a keyboard and a screen to disable ufw but it still doesn't work. Can someone help me?

If it helps, this is the output of ufw status:

```
To            Action      From                  
--            ------      ----
22            ALLOW       192.168.0.0/24             # allow SSH from local LAN
Anywhere      ALLOW       192.168.0.0/24 1900/udp    # allow local LAN SSDP for UPnPdiscovery
9735          ALLOW       Anywhere                   # allow Lightning
8333          ALLOW       Anywhere                   # allow Bitcoin mainnet
18333         ALLOW       Anywhere                   # allow Bitcoin testnet
9735 (v6)     ALLOW       Anywhere (v6)              # allow Lightning
8333 (v6)     ALLOW       Anywhere (v6)              # allow Bitcoin mainnet
18333 (v6)    ALLOW       Anywhere (v6)              # allow Bitcoin testnet

**Comment by Stadicus** [comment]
Do you think it's an issue with the SSH keys? If so, you can enable the login without keys again (comment the lines again). 

Regarding UFW, what is the IP address of your Pi? for the above mentioned config, it needs to be something like `192.168.0.*`.

**Comment by dlawant** [comment]
That was it! Things are working normally again. The UFW config was correct.

Tks!
