### ISSUE TITLE
LND wont run after installing tor

### ISSUE THREAD

**Issue by RobJah** [Stadicus/guides#308]
Hi there,

I had a lightning node running fine, with the stadicus guide. Now today i wanted to add TOR, just for the hell of it. Eventhough I did exactly what the guide says, im stuck. 

First problem: my node isnt reachable via https://bitnodes.earn.com/
I did everthing i could, checked the ufw and portforwarding and found nothing strange. 

so long story short, the command 'bitcoin-cli getpeerinfo | grep  local' gives me: 
    "addrlocal": "80.127.116.96:19497",
    "addrlocal": "77.247.181.162:51194",
    "addrlocal": "qwe54z7pugw7ilvh.onion:8333",
    "addrlocal": "185.220.101.20:44693",
    "addrlocal": "94.230.208.147:50422",
    "addrlocal": "66.70.217.179:47596",
    "addrlocal": "176.10.99.200:42588",
    "addrlocal": "185.104.120.4:48701",
    "addrlocal": "158.174.122.218:58348",

*qwe54z7pugw7ilvh.onion:8333 is my tor node adress

BUT the command 'curl icanhazip.com' gives me my reguler public IP. So im confused what this means and if tor works or not. 

Second problem, I went on with the process of Setup LND for Tor. To start i couldnt find 'nat=true' in my /home/bitcoin/.lnd/lnd.conf, so I only added the [Tor] lines and saved the file.

Afterwards the guide says u need start LND, which i did, and now it give me crap like:
admin@RaspiBolt:~ $ systemctl status lnd
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-12-23 15:25:30 CET; 15s ago
  Process: 798 ExecStart=/usr/local/bin/lnd --externalip=${PUBLICIP} (code=exited, status=1/FAILURE)
 Main PID: 798 (code=exited, status=1/FAILURE)
admin@RaspiBolt:~ $ sudo journalctl -f -u lnd
-- Logs begin at Sun 2018-12-23 15:21:35 CET. --
Dec 23 15:24:30 RaspiBolt systemd[1]: Started LND Lightning Daemon.
Dec 23 15:24:30 RaspiBolt systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Dec 23 15:24:30 RaspiBolt systemd[1]: lnd.service: Unit entered failed state.
Dec 23 15:24:30 RaspiBolt systemd[1]: lnd.service: Failed with result 'exit-code'.
Dec 23 15:25:30 RaspiBolt systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Dec 23 15:25:30 RaspiBolt systemd[1]: Stopped LND Lightning Daemon.
Dec 23 15:25:30 RaspiBolt systemd[1]: Started LND Lightning Daemon.

Please assist xD

**Comment by Stadicus** [comment]
There seems to be an issue with bitnodes, check out this method:
https://github.com/Stadicus/guides/issues/189#issuecomment-449638447

To debug LND, check out the Troubleshooting section:
https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_70_troubleshooting.md#lnd
