### ISSUE TITLE
EPS: Error with bitcoin json-rpc

### ISSUE THREAD

**Issue by jodobear** [Stadicus/guides#319]
I've been trying to setup my raspiblitz with eps and followed the instructions to the T, but i'm getting the following error:

``` JsonRpcConnectionError('authentication for JSON-RPC failed',)```

So, i thought i might have made a typo or some stupid mistake. I checked all the config files in ```/home/bitcoin/.bitcoin/bitcoin.conf``` ```/home/admin/.bitcoin/bitcoin.config``` & ```~/eps/config.cfg``` for ```rpc_user``` & ```rpc_password``` and they are identical.

So, what am i missing or doing wrong?

Thank you!

**Comment by Stadicus** [comment]
Working on updating the EPS guide, there have been some major changes.

**Comment by jodobear** [comment]
Is this about RPC username/password method being depricated? I'm gonna try to change it to the cookie method. Will post if i can resolve it or find something.

**Comment by Stadicus** [comment]
The RPC user/pw is still the way to go, no changes there.

**Comment by jodobear** [comment]
I updated my Pi's image with LND 0.5.1, and it worked seamlessly. I still don't know why did i face that problem, would like to know that. But, for now my problem has been resolved but the question still remains.

Using RPC user/pw for authentication.

**Comment by Stadicus** [comment]
Closing for now. If you come accross an answer, I would be interested as well. :-)
