### ISSUE TITLE
Bonus: Add LND externalip:port to system overview script

### ISSUE THREAD

**Issue by robclark56** [Stadicus/guides#32]
"Ressources free"
in 
/usr/local/bin/raspibolt

**Comment by robclark56** [comment]
Suggestion:

In the Bitcoin column, you show 
xx.xx.xx.xx:18333

In the LND column, would be nice to also display 
<externalip>:<port> as LND as currently using (i.e. as used when starting the lnd service with --externalip)

PLUS the output of curl ipinfo.io/ip  (i.e. the current IP address) ....and highlight in RED if the CURRENT IP is not the same as LND --externalip  (which can happen if the external IP has changed since lnd was started)


:-)

**Comment by Stadicus** [comment]
For your other suggestions: I'll happily accept a pull request. :-)
