### ISSUE TITLE
Should indexes folder be included during mainnet transfer?

### ISSUE THREAD

**Issue by Septem151** [Stadicus/guides#324]
At this step of the guide: https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_50_mainnet.md#copy-the-mainnet-blockchain

where you transfer the mainnet blockchain data over SSH/SCP, it's stated to only transfer over the `blocks` and `chainstate` folders. However, there is a third folder listed in my directory titled `indexes` which has a subfolder `txindex`.

Is it necessary to transfer this `indexes` folder over as well? I would assume yes, since this contains the data relevant to txindex. I'm unsure if this is a new data structure change in the most recent release of Bitcoin Core, or if the guide is somehow incorrect.

**Comment by Stadicus** [comment]
Thanks for pointing out this inconsistency. I think you're right, that change must have slipped by with the upgrade to Bitcoin Core 0.17 (have not checked).

As I was thinking about removing the `txindex=1` option for some time now, I took this issue to finally do it. Problem solved! :-)

More reasoning here:
https://twitter.com/Stadicus3000/status/1079677441956868097
