### ISSUE TITLE
lncli --network=testnet np2wkh rpc error

### ISSUE THREAD

**Issue by Nursing-Guy** [Stadicus/guides#326]
>$` [lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused

I've messed with my bitcoin.conf file based on some other issues I read through. My rpcpassword is already all simple characters, my rpcuser now matches the name of the node under raspi-config.  I don't know where that tcp comes from as my .conf file matches the /bitcoin portion of the guide

**Comment by Stadicus** [comment]
The error above does not concern `bitcoind` but the gRPC API that is exposed by LND itself and can be used to connect to LND, eg. as a wallet or web interface.

* are you running additional software that connects to LND on this port?
* is your port opened in UFW?

**Comment by Nursing-Guy** [comment]
This is a fresh install of LND on a device I wiped clean. Unless the guide is installing LND on the external hard drive and it didn't get written over on the fresh install.

I'm looking into UFW right now, but the command I'm calling is `lncli --network=testnet np2wkh`

**Comment by Nursing-Guy** [comment]
I've left the program running for the past two days since I've been busy with other tasks. I just attempted to recreate the error and received the proper response. I'm uncertain of the cause, but I suspect that either the lightning network or the bitcoin client weren't caught up to the network. I believe the guide shows how to check this, I likely just misinterpreted the results of the calls.

**Comment by Nursing-Guy** [comment]
I now have a working LND node. I have to get to work but I'm excited to get some blockachinos. I've learned a lot, I am super thankful to you Stadicus for writing this guide and being so helpful with this Linux and LND newcomer. I've learned a lot about how much more there is to learn and it will probably be a little while before I get #Reckless
