### ISSUE TITLE
Tor V3 Onion on v 0.99

### ISSUE THREAD

**Issue by zer0trst** [Stadicus/guides#328]
Hello to all and Happy New Year!

Hoping to get some assistance on this one. I am trying to run through TOR v3 onion service. I have Setup my Raspiblitz today using the latest image (raspiblitz-0.99-2018-12-24.img.gz)

I tried the new option of setting from the main menu:  Go to SERVICES and Run behind TOR
![image](https://user-images.githubusercontent.com/46293453/50574423-2b5b4200-0e34-11e9-89f4-94bceee122e6.png)

It gives me this screen for a split second and then takes me back to the main menu. From there it does nothing further.

![image](https://user-images.githubusercontent.com/46293453/50574437-5fcefe00-0e34-11e9-9afd-cbb625e1d557.png)

I rebooted in the hopes it would do something but still nothing..

So I went and Followed the steps outlined here: https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_69_tor.md

added sources and installed tor-arm...

Added "bitcoin" to the group "debian-tor"

      $ cat /etc/group | grep debian-tor
         debian-tor:x:123:bitcoin

un-commented and added in "torrc" file

      $ sudo nano /etc/tor/torrc

![image](https://user-images.githubusercontent.com/46293453/50574653-11236300-0e38-11e9-95a7-dde70e09f4e5.png)

Added lines to "bitcoin.conf" file

      $ sudo nano /home/bitcoin/.bitcoin/bitcoin.conf

![image](https://user-images.githubusercontent.com/46293453/50575217-a8db7e00-0e45-11e9-87e3-ad612c1940f3.png)

Archived log file and restarted bitcoin core

      $ sudo mv /home/bitcoin/.bitcoin/debug.log /home/bitcoin/.bitcoin/debug.log.old
      $ sudo systemctl start bitcoind

ran the verification 

      $ sudo tail /home/bitcoin/.bitcoin/debug.log -f -n 200

![image](https://user-images.githubusercontent.com/46293453/50574715-b68b0680-0e39-11e9-9fb4-caf63527aed1.png)
![image](https://user-images.githubusercontent.com/46293453/50575043-3916c480-0e40-11e9-992c-ae2b9e8b9048.png)

and 

      $ bitcoin-cli getnetworkinfo

![image](https://user-images.githubusercontent.com/46293453/50574850-711c0880-0e3c-11e9-916b-42dea1388442.png)

Everything looks right i think? but here's where I run into a brick wall....

I run 

    $ curl icanhazip.com

and my IP shows up:

![image](https://user-images.githubusercontent.com/46293453/50574831-ffdc5580-0e3b-11e9-8ad9-c06feb9f8cda.png)

Now when I run 

      $ bitcoin-cli getpeerinfo | grep  local

my IP is not included but my onion address is...

![image](https://user-images.githubusercontent.com/46293453/50574904-7037a680-0e3d-11e9-949b-97e9baf47565.png)

So i then go through the steps for LND as follows: 

      $ sudo nano /home/bitcoin/.lnd/lnd.conf

![image](https://user-images.githubusercontent.com/46293453/50574938-2ac7a900-0e3e-11e9-8802-f480a93ff5b2.png)

and when I run

      lncli getinfo 
      lncli getnodeinfo [YOUR_PUBKEY]

My IP is exposed here as well

![image](https://user-images.githubusercontent.com/46293453/50574974-ee487d00-0e3e-11e9-95ca-18a4dab2608c.png)
![image](https://user-images.githubusercontent.com/46293453/50574990-3d8ead80-0e3f-11e9-95b0-b9769a06ba66.png)

So final thing I have tried is adding these lines to "/etc/tor/torrc" as someone on reddit had pointed out a few months back

![image](https://user-images.githubusercontent.com/46293453/50575062-e984c880-0e40-11e9-8563-bf7de4cb2cbd.png)

then I grabbed the address out of /var/lib/tor/lnd_service/hostname and added it to /home/bitcoin/.lnd/lnd.conf in "externalip"

not sure i've put this in the right place or not??

![image](https://user-images.githubusercontent.com/46293453/50575078-8a738380-0e41-11e9-99dd-85fd152f67d9.png)

This seems to have done something because after waiting about 10 minutes, when I run 

     lncli getinfo

Under URI's I now get both my public key against my exposed IP but also my public key against what appears to be a V3 onion address but it's not the address in /var/lib/tor/lnd_service/hostname or what I put under "externalip" in lnd.conf

![image](https://user-images.githubusercontent.com/46293453/50575166-29997a80-0e44-11e9-9e2e-df274f1c7238.png)
![image](https://user-images.githubusercontent.com/46293453/50575194-f3a8c600-0e44-11e9-8b2f-92790d23807d.png)

![image](https://user-images.githubusercontent.com/46293453/50590253-ec7dc880-0ed5-11e9-80e2-6d55316de922.png)

so i'm stuck here..

any ideas? something I've missing along the way perhaps?

**Comment by Stadicus** [comment]
Wow, I think this is the first issue that forced me to work in parallel windows... :-)

**Tor on Bitcoin Core**
seems to work perfectly well
* Tor is running
* onion address is created and used to connect to Bitcoin p2p network
* Bitcoind traffic for ipv4 & ipv6 is routed over Tor proxy

It is perfectly normal that your IP is exposed when you call a normal internet address like icanhazip.com, that has nothing to do with Tor or Bitcoin. This command is only used to get the reference clearnet address (I should make that more clear in the guide). The fact that you cannot find your IP address in "getpeerinfo" verifies that bitcoind does not use your clearnet address.

**Tor for Lightning**
there might be an issue
* the commands listed should suffice to completely deactivate that your node is announced on clearnet. I can reliably switch between clearnet & Tor by just changing the lnd.conf.
* additional steps like you described should not be necessary.
* did you restart LND?

**Comment by zer0trst** [comment]
Hey Stadicus thanks for getting back to me. 

Had an inkling that the the icanhazip report was right thanks for confirming. 

I did restart LND but nothing has changed. I am going to format my SD, restart all over again and see if anything changes just in case there was something I did wrong somewhere. I have also shared this over at rootzoll/raspiblitz to see if anyone there has any ideas

I'll report my findings

Thanks for your help! :)

**Comment by Stadicus** [comment]
I guess, you also see your clearnet address with `lncli getinfo`? This should definitely not be the case. Please check with the RaspiBlitz project why that could be. In my experience, the changes highlighted in my guide work reliably, but I might not be aware of specific configurations that RaspiBlitz implementend.

Closing for now (cannot support other projects), but would appreciate feedback if you figure it out.

**Comment by zer0trst** [comment]
@Stadicus thanks for your help. 

To save anyone else the confusion , I ended up getting a resolve:

In the Raspiblitz 0.99 menu under Services you have to press space-bar on "Run behind TOR" to make your selection then hit enter and it runs the tor setup script.

I wasn't hitting space bar to make the selection so subsequently nothing would happen when I hit enter... (Facepalm :P) - 

This will only run Onion V2 service though. Now when I run 

        lncli getnodeinfo >pub key< 

I only get my onion address - IP doesnt show up at all.

Thanks! :)
