### ISSUE TITLE
LND Configuration

### ISSUE THREAD

**Issue by Kartereo** [Stadicus/guides#329]
I have just gone through and everything is now working up until LND Configuration. Thank you for updating the guide by the way ;-). I am getting the following while using the new LND 0.5.1 beta.

enable and start LND
$ sudo systemctl enable lnd
$ sudo systemctl start lnd
$ sudo systemctl status lnd
monitor the LND logfile in realtime (exit with Ctrl-C)
$ sudo journalctl -f -u lnd

admin@thundroid:~/download$ sudo systemctl status lnd
● lnd.service - LND Lightning Daemon
   Loaded: loaded (/etc/systemd/system/lnd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2019-01-01 19:43:49 EST; 5s ago
  Process: 1812 ExecStart=/usr/local/bin/lnd (code=exited, status=1/FAILURE)
 Main PID: 1812 (code=exited, status=1/FAILURE)

Jan 01 19:43:49 thundroid systemd[1]: lnd.service: Unit entered failed state.
Jan 01 19:43:49 thundroid systemd[1]: lnd.service: Failed with result 'exit-code'.
admin@thundroid:~/download$ sudo journalctl -f -u lnd
-- Logs begin at Tue 2019-01-01 00:20:21 EST. --
Jan 01 19:42:48 thundroid systemd[1]: Started LND Lightning Daemon.
Jan 01 19:42:49 thundroid systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Jan 01 19:42:49 thundroid systemd[1]: lnd.service: Unit entered failed state.
Jan 01 19:42:49 thundroid systemd[1]: lnd.service: Failed with result 'exit-code'.
Jan 01 19:43:49 thundroid systemd[1]: lnd.service: Service hold-off time over, scheduling restart.
Jan 01 19:43:49 thundroid systemd[1]: Stopped LND Lightning Daemon.
Jan 01 19:43:49 thundroid systemd[1]: Started LND Lightning Daemon.
Jan 01 19:43:49 thundroid systemd[1]: lnd.service: Main process exited, code=exited, status=1/FAILURE
Jan 01 19:43:49 thundroid systemd[1]: lnd.service: Unit entered failed state.
Jan 01 19:43:49 thundroid systemd[1]: lnd.service: Failed with result 'exit-code'.

**Comment by Stadicus** [comment]
Can you please go through the Troubleshooting guide and provide additional logs / unexpected behaviour?
https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_70_troubleshooting.md#lnd
