### ISSUE TITLE
[ERR] Disc: unable to validate channel update announcement  / invalid signature for channel update / unable to validate node announcement

### ISSUE THREAD

**Issue by thetruplaya** [Stadicus/guides#332]
Everything seems to be running , just seeing a lot of these in the lnd process. what does it mean?

I normally see something like Updated vertex data for node blah blah blah broadcasting batch of updates 20 or something like that. But lately Ive been seeing more of errors like in the title bar.

Did i miss a update or something? Any incite would be grateful. thanks

**Comment by Stadicus** [comment]
Cannot say from the top of my head. Might be worth asking in the Slack / investigating the LND repo.

**Comment by thetruplaya** [comment]
thanks man.
