### ISSUE TITLE
Systemct1 command not working 

### ISSUE THREAD

**Issue by paintufast** [Stadicus/guides#334]
On your raspberry pi setup page during UFW setup I can complete all steps except for one that is causing the following error to display. I have tried adding, "sudo" and executing command from multiple users (root, admin, bitcoin) all with no success. 

systemct1 enable ufw
error: 
bash:systemct1:command not found

**Comment by Fillippone** [comment]
Maybe it is not systemct1, but systemctl? (l like small L)

**Comment by paintufast** [comment]
Yeah that fixed it. My mistake. Thank you.
