### ISSUE TITLE
Instructions on how to renew pubkey

### ISSUE THREAD

**Issue by beinardus** [Stadicus/guides#335]
In the instructions on how to install Tor for LND, this is one of the recommendations:

"In case you have been running a node on clearnet before, it is recommended to close all Lightning channels and start a brand new node on Tor."

It would be nice to know how this can be achieved. I think the only goal here is a new pubkey.
This is what I did:
* closed all open channels
* waited 24h on the pending forced-close channels
* moved the balance of the LND wallet back to my real wallet
* made a backup of all LND related directories on the HDD
* removed all LND related directories from the HDD
* started LND and fixed all errors manually (like restoring the macroon files and certificates)
* created a new wallet

It would also be nice to know how to renew the onion address.

**Comment by BobleChinois** [comment]
What I did were the same steps than OP, except for "removed all LND related directories", feels a bit overkill but maybe I'm wrong. 
As for renewing the .onion address that's a good question, I'll have to do some research myself on that.

**Comment by Stadicus** [comment]
Any update on how to renew the .onion address?
