### ISSUE TITLE
Clearing logs

### ISSUE THREAD

**Issue by MattThurling** [Stadicus/guides#35]
In the Known Issues section at the end of Mainnet you give a fix for systems that run out of space due to the logs (which works fine)

Typo?

$ cd /var/logs

Should be

$ cd /var/log

**Comment by Stadicus** [comment]
Thanks, fixed: https://github.com/Stadicus/guides/commit/3b3ba77b41e15d81ff4eb85a6afbcc7dcfeb8b7f
