### ISSUE TITLE
Huge Shango QR code

### ISSUE THREAD

**Issue by MrPaz** [Stadicus/guides#354]
I got to the end of the bonus guide to set up Shango with my lightning node, and when I do

`echo -e "$(curl -s ipinfo.io/ip),\n$(xxd -p -c2000 ~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon)," > qr.txt && cat ~/.lnd/tls.cert >>qr.txt && qrencode -t ANSIUTF8 < qr.txt`

it generates a QR that is huge. I maximize my putty terminal, but cannot fit the entire QR code on the monitor (1920x1080), and thus cannot scan it with the app.  Any advice (besides get a higher resolution monitor)?

**Comment by openoms** [comment]
Before you run the command maximize the window and click on 'View' - > 'Zoom out'  in the menu of the terminal. I can fit it easily to an even smaller res monitor.

**Comment by Stadicus** [comment]
Did that work, @MrPaz?

**Comment by MrPaz** [comment]
Well, luckily I'm running a light desktop (raspbian stretch lite + pixel) and was able to install gnome-terminal in order to zoom out (raspbian native terminal does not zoom).  I suppose this would work ssh'ing in via another linux machine too.  However, I was never able to get a QR of proper, scanable size using windows, PuTTy.  So I guess the work around is to use a linux computer to ssh, zoom out via that linux terminal, and scan the QR, but not sure why it was so huge in the first place or how to zoom out in windows.  

To be clear this was the QR code for LND 0.5 produced via `echo -e "$(curl -s ipinfo.io/ip),\n$(xxd -p -c2000 ~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon)," > qr.txt && cat ~/.lnd/tls.cert >>qr.txt && qrencode -t ANSIUTF8 < qr.txt.`  
The earlier QR code command `echo -e "$(curl -s ipinfo.io/ip),\n$(xxd -p -c2000 admin.macaroon)," > qr.txt && cat tls.cert >>qr.txt && qrencode -t ANSIUTF8 < qr.txt` was a reasonable size.
