### ISSUE TITLE
Moving the Swap File - Permission

### ISSUE THREAD

**Issue by DanielHinton** [Stadicus/guides#356]
Running `$ sudo dphys-swapfile swapoff` I get `sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set`.

I've seen @Stadicus say "Removing the swap file is pretty optional, I wouldn't worry too much about that." Does this mean that I'd be OK skipping the entire "Moving the Swap File" section or is this error message a sign of a larger permissions issue that will trip me up later in the process?

**Comment by Stadicus** [comment]
No, you should definitely put the swap file to the external hdd, as the heavy i/o writing can damage your sdcard physically. Just **removing** the old swap file is optional, as it takes some space but is just some uncollected garbage.
