### ISSUE TITLE
Failed to stop lnd.service

### ISSUE THREAD

**Issue by jbrodskytd** [Stadicus/guides#369]
Hi I'm running into an issue when trying to use systemctl to stop my lnd.service

```
$ sudo systemctl stop lnd
Failed to stop lnd.service: Failed to activate service 'org.freedesktop.systemd1': timed out
See system logs and 'systemctl status lnd.service' for details.
Failed to get load state of lnd.service: Connection timed out
```

Any ideas? my node has been up and running for a few weeks now.

**Comment by Stadicus** [comment]
Can you run through the "Troubleshoot" section and paste relevant log files here?

**Comment by daniel-vera-g** [comment]
> Hi I'm running into an issue when trying to use systemctl to stop my lnd.service
> 
> ```
> $ sudo systemctl stop lnd
> Failed to stop lnd.service: Failed to activate service 'org.freedesktop.systemd1': timed out
> See system logs and 'systemctl status lnd.service' for details.
> Failed to get load state of lnd.service: Connection timed out
> ```
> Any ideas? my node has been up and running for a few weeks now.

Was lnd.service running at all?

What does `systemctl status lnd.service` output?
What are the logs saying?

**Comment by jbrodskytd** [comment]
Thanks guys, I ended up doing a hard restart of my raspibolt... none of the system commands would work but Lnd was running and I can run lncli commands. Seems to be working ok now. If I run into it again I'll do as Stadicus suggested. Thanks again!
