### ISSUE TITLE
Liquid Sidechain

### ISSUE THREAD

**Issue by Amiga500** [Stadicus/guides#385]
This is not a bug.. but a request

It could be nice if someone that has installed Liquid Sidechain client on raspberry pi.. to help and add on this fantastic project :) (https://github.com/Blockstream/liquid)

After bitcoin core and lightning network lnd, it's time for the first serious sidechain :)

**Comment by Stadicus** [comment]
Haven't tried it on a RPi yet, but I think it needs way more resources due to 1min blocks and computing-intensive confidential transactions. I don't think that would work,but if anyone tried it, feedback is appreciated.
