### ISSUE TITLE
Switching between Mainnet and Testnet

### ISSUE THREAD

**Issue by walterkok** [Stadicus/guides#388]
Hi Stadicus, I have one simple question. Everything is working well on mainnet now for some weeks but if I want to move back to testnet (and later back to mainnet etc.), my understanding of reading all directories and your instructions is that I only need to adjust the following
0) stop lnd and bitcoind
1) change to testnet in /home/bitcoin/.bitcoin/bitcoin.conf
2) chainge to testnet in /home/admin/.bitcoin/bitcoin.conf
3) change to testnet in /home/bitcoin/.lnd/lnd.conf
I think the admin.macaroon is already available in both mainnet and testnet (also for user admin) and also the tls.cert does not have to change? 
so after 1), 2) and 3) start bitcoind and than lnd should have it all work on testnet again?
And to go back to mainnet just do the config files back to mainnet

Before I am going to destroy a working node, I just wanted to check, thanks! Walter

**Comment by Stadicus** [comment]
Reading through your very thorough list, I think that's exactly right. 👨‍🚀👍
