### ISSUE TITLE
System Overview -- Resources free now shows SSD at 0%

### ISSUE THREAD

**Issue by beeforbacon1** [Stadicus/guides#405]
Everything seems to be running just fine, but for some reason suddenly it shows SSD is red with 0% . What does this mean? What happened? thank you.

**Comment by beeforbacon1** [comment]
will reopen with more details in time

**Comment by Stadicus** [comment]
THe welcome script is just meant as a high level monitoring info. It may not fit your system, if you have a slightly different setup. Can you try with the appropriate Linux commant `df -h`?
