### ISSUE TITLE
Stuck in a loop 

### ISSUE THREAD

**Issue by PBJellytime** [Stadicus/guides#409]
My node was running fine then had a power supply failure so replaced and rebooted but something must have corrupted as each time I reboot now it gets to the Lightning Filtering Blockchain ?/567391 then prompts for the LND wallet password which when entered generates the below error message

[lncli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

**Comment by Stadicus** [comment]
The "all SubConns are in TransientFailure" and the rest of the error message means that the lnd grpc api is not responding. My guess is that LND does not start correctly. 

Can you provide some relevant log excerpts, e.g. by posting them to pastebin.com? The most current log file is located at `/home/bitcoin/.lnd/logs/bitcoin/mainnet/lnd.log`.
