### ISSUE TITLE
suggestion: 2 partitions for the rpi hdd guide

### ISSUE THREAD

**Issue by phenomeus** [Stadicus/guides#417]
hi Stadicus,

i had my hdd format to exfat, because its easier to "reindex" the blockchain on a Mac with 16GB ram if something goes wrong. but then I couldn't do my swap file of course, because that needs ext4 as a fs. so I resized my exfat partition with this one and only free tool under windows (super quick, no data lost) and created an ext4 2GB partition at the end. 

I mounted both with fstab and followed your guide to enable swap but put it on the new ext4 partition. working flawless. maybe you want to add that. I'm pretty happy. and very flexible to detach the drive and attach and read from the main exfat partition on windows and Mac. 

here is my fstab:
umask 1001 is my "bitcoin" user

UUID=123 /mnt/hdd exfat defaults,auto,nofail,uid=1001,umask=0001,gid=1001,rw 0 0
UUID=456 /mnt/swap ext4 noexec,defaults 0 0

**Comment by Stadicus** [comment]
Nice, thanks for the info. The fact that the Pi does not have enough power to index / validate the blockchain makes it quite hard to have the "best" setup, there are always compromises. As I'm not a big fan of exFAT partitions for server (personal opinion), I'll leave it for the moment.
