### ISSUE TITLE
Missing dirmngr

### ISSUE THREAD

**Issue by lmfmaier** [Stadicus/guides#422]
When executing gpg --refresh-keys I got the following errors:

`gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/run/user/1000/gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver refresh failed: No dirmngr`

You need to install dirmngr:

`sudo apt-get install dirmngr --install-recommends`

This solves the issue

**Comment by Stadicus** [comment]
Thanks for the pointer, fixed.
https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_20_pi.md
