### ISSUE TITLE
mkdir /mnt/hdd/electrum-personal-server -permission denied

### ISSUE THREAD

**Issue by walletofsatoshi** [Stadicus/guides#431]
bitcoin is not in the sudoers file.  This incident will be reported.

getting stuck here with this error while installing EPS. Please help

**Comment by Stadicus** [comment]
All `sudo` commands need to be run as user "admin". The other users are resticted from sudo permissions for security reasons.

**Comment by walletofsatoshi** [comment]
It’s a raspiblitz setup had to edit sudoers to allow bitcoin as user to get it working. But having now issues running the server getting error as config file non existent despite following and editing saving the simple file do we have to specify datadir in the config file?

**Comment by Stadicus** [comment]
I am not familiar with the RaspiBlitz in detail, I suggest posting the question directly to their repository. 

In general it's safe to assume that the "bitcoin" user is not supposed to be sudo. Isn't there a "admin" or "root" user for that purpose?

**Comment by walletofsatoshi** [comment]
I used your guide to get EPS Installed which has user as bitcoin there is no separate guide fir raspi blitz EPS yet . I finally seem to get it working will keep you posted
