### ISSUE TITLE
Invalid fstab entry

### ISSUE THREAD

**Issue by beinardus** [Stadicus/guides#434]
I think the fstab entry lost it's file system:
UUID=123456 /mnt/hdd rw,nosuid,dev,noexec,noatime,nodiratime,auto,nouser,async,nofail 0 2

must be:
UUID=123456 /mnt/hdd ext4 rw,nosuid,dev,noexec,noatime,nodiratime,auto,nouser,async,nofail 0 2

error:
mount: unknown filesystem type 'rw,nosuid,dev,noexec,noatime,nodiratime,auto,nouser,async,nofail'

**Comment by LevonTostig** [comment]
Seconded.

**Comment by Stadicus** [comment]
Thanks for pointing that out, embarrassing... Fixed.
