### ISSUE TITLE
Server socket address already in use - EPS

### ISSUE THREAD

**Issue by woodscoin** [Stadicus/guides#435]
On closing and restarting EPS directly it crashed with the following error message:
`OSError: [Errno 98] Address already in use`
The kernel probably saves the socket state and keeps listening after a reboot.
I found that changing RestartSec=60 to RestartSec=120 in the systemd unit for automatic start on boot resolved the issue.

**Comment by walletofsatoshi** [comment]
Simply restarting eps resolved this for me

**Comment by Stadicus** [comment]
Thanks, will test for next update.
