### ISSUE TITLE
Mounting External Hard disk (Raspibolt)

### ISSUE THREAD

**Issue by vellarod** [Stadicus/guides#436]
I had to include ext4 in command of fstab file to work on reboot. [/tab] represents tab

UUID=123456 [tab] /mnt/hdd [/tab] ext4 [/tab] rw,nosuid,dev,noexec,noatime,nodiratime,auto,nouser,async,nofail [/tab] 0 [/tab] 2

**Comment by LevonTostig** [comment]
Seconded.

**Comment by Stadicus** [comment]
Thanks for pointing that out, embarrassing... Fixed: https://github.com/Stadicus/guides/commit/c7c80c76cbd3a8022c9b6707add49134a3f72a36
