### ISSUE TITLE
ufw and fail2ban not in repositories

### ISSUE THREAD

**Issue by wolfgang-boku** [Stadicus/guides#47]
The packages ufw and fail2ban are not in the current raspbian repositories. I suggest removing those from the guide, adding instructions on how to install them anyway, or modify the section using alternative approaches.

Otherwise, I have worked through major parts of this nicely prepared guide without problems, thanks!

**Comment by Stadicus** [comment]
Hi Wolfgang, the packages `ufw` and `fail2ban` are definitely in the standard repositories if you used the current Raspbian Stretch and updated your information with `sudo apt-get update`.

```
admin ~ ฿ apt-cache showpkg ufw
Package: ufw
Versions:
0.35-4 (/var/lib/apt/lists/raspbian.raspberrypi.org_raspbian_dists_stretch_main_                                                                                                             binary-armhf_Packages)

admin ~ ฿ apt-cache showpkg fail2ban
Package: fail2ban
Versions:
0.9.6-2 (/var/lib/apt/lists/raspbian.raspberrypi.org_raspbian_dists_stretch_main_binary-armhf_Packages)
```

**Comment by wolfgang-boku** [comment]
You're right, Stadicus. Sorry for the wrong comment! Not sure what I did wrong in the first place (I thought I did update before trying to install the packages), but now it works.
