### ISSUE TITLE
Access credentials

### ISSUE THREAD

**Issue by sobchek** [Stadicus/guides#55]
I misread your comment about not changing the password when moving to mainnet. What do you mean by 'recreate access credentials?'

Thanks

**Comment by sobchek** [comment]
I have tried moving *.macaroon files and macaroon directory outside of the .lnd, tried 'unlock' and failed / tried 'create' and failed...

**Comment by Stadicus** [comment]
You need to delete (ore move) the 
* the `*.macaroon` files, 
* the `macaroons.db` file, but also 
* the `wallet.db` (located in `~/.lnd/data/chain/bitcoin/mainnet`)

and recreate the wallet / macaroons from scratch. Be careful not to lock up any funds by closing all channels before you do that.

**Comment by sobchek** [comment]
Bingo! Thanks Stad.
