### ISSUE TITLE
some issue on the guide

### ISSUE THREAD

**Issue by Amiga500** [Stadicus/guides#69]
From the manual:
Adding main user "admin"
This guide uses the main user "admin" instead of "pi" to make it more reusable with other platforms.

Create the new user and add it to the group "sudo"
$ sudo adduser admin ***
$ sudo adduser admin sudo
Set the password to your password [A] and set the standard shell (command line interface) to "bash"
$ sudo passwd admin <---- THIS LINE IS NOT NECESSARY IN MY OPINION (THE PASSWORD IS REQUESTED JUST AT ***)

-------------------------------------------------------------------------------------------------------------------

From the manual:
Prepare Bitcoin Core directory
We use the Bitcoin daemon, called “bitcoind”, that runs in the background without user interface and stores all data in a the directory /home/bitcoin/.bitcoin. Instead of creating a real directory, we create a link that points to a directory on the external hard disk.

Change to user “bitcoin” and enter the password.
$ sudo su bitcoin <---- DOING THIS COMMAND FROM ADMIN, IT DOESN'T REQUEST THE PASSWORD LIKE WROTE IN THE COMMENT

IS NOT SPECIFY TO LOGIN WITH ADMIN, (BETTER TO SPECIFY).

**Comment by Stadicus** [comment]
Thanks for your feedback, I updated the guide with both suggested changes!

**Comment by Amiga500** [comment]
Thanks a lot for your guide! It's the best on internet ;)
