### ISSUE TITLE
sudo needed when setting up bitcoin.conf

### ISSUE THREAD

**Issue by svanstaa** [Stadicus/guides#77]
only a minor annoyance, but instead of

$ nano /home/bitcoin/.bitcoin/bitcoin.conf

it should be

$ sudo nano /home/bitcoin/.bitcoin/bitcoin.conf

otherwise the user will find that he cannot save the edited file.

**Comment by Stadicus** [comment]
You should not need sudo, as this command is expected to be executed in a `bitcoin` user session (see `sudo su bitcoin` before).

If you set it up with `sudo`, the user "bitcoin" will not be owner of the file.

**Comment by svanstaa** [comment]
You are correct :). I must have overlooked that line.
