### ISSUE TITLE
With Bitcoin Core 0.16.1 and LND 0.4.2 ram usage is very low on Raspberry Pi 3 B Plus

### ISSUE THREAD

**Issue by Amiga500** [Stadicus/guides#84]
With Bitcoin Core 0.16.1 and LND 0.4.2 ram usage is very low on Raspberry Pi 3 B Plus.

![raspibolt_memory](https://user-images.githubusercontent.com/16525337/41505752-a9426c64-720f-11e8-9df7-54df3e2c36ea.png)

**Comment by Stadicus** [comment]
With "RAM usage is very high" you mean "very low"? :-)

**Comment by Amiga500** [comment]
Sure, with a little of sarcasm :) 
I continue to play with https://poketoshi.com/ now :)

**Comment by Stadicus** [comment]
Nice! Already thought I had to hold off my upgrade plans...
