### ISSUE TITLE
Bitcoin Core Update to 0.16.1

### ISSUE THREAD

**Issue by waffi121** [Stadicus/guides#88]
Short question about the update to 0.16.1

BTC and Lightning stop with:

bitcoin-cli stop
sudo systemctl stop lnd

Download with:

 wget https: //bitcoin.org/bin/bitcoin-core-0.16.1 ...
tar -xvf bitcoin-0.16.1-arm-linux-gnueabihf.tar.gz
sudo install -m 0755 -o root -g root -t / usr / local / bin bitcoin-0.16.1 / bin / *

Then reactivate with:
sudo systemctl start lnd

Check the BTC version:

bitcoind --version

Should everything be for the update? :)

Thank you!

**Comment by Amiga500** [comment]
Try this (with admin user):

$ sudo systemctl stop lnd
$ sudo systemctl stop bitcoind

cd /home/admin/download
wget https://bitcoin.org/bin/bitcoin-core-0.16.1/bitcoin-0.16.1-arm-linux-gnueabihf.tar.gz
tar -xvf bitcoin-0.16.1-arm-linux-gnueabihf.tar.gz
sudo install -m 0755 -o root -g root -t /usr/local/bin bitcoin-0.16.1/bin/*

$ sudo systemctl start bitcoind
$ sudo systemctl start lnd

**Comment by waffi121** [comment]
thank you works fine :)
