### ISSUE TITLE
Dashboard to manage own full lightning node. 

### ISSUE THREAD

**Issue by giulnz** [Stadicus/guides#91]
Hi, thanks Stadicus for your guide.
I find lnd.fun, a "Panel for webmasters to manage their full lightning node" but i don't know how to implement and no find info about it.
Someone know a dashboard project for our LN node or how to use that one that i found ?

**Comment by Stadicus** [comment]
Yes, http://lnd.fun/ looks gorgeous. Unfortunately, there's no documentation as of now, and no information about the project...

Two better documented projects, that should run without issues:
* https://github.com/altangent/lnd-explorer
* https://github.com/mably/lncli-web

**Comment by Stadicus** [comment]
BTW: the iOS & Android app Shango wallet works great to manage basic stuff incl. channels.
https://github.com/neogeno/shango-lightning-wallet

**Comment by Stadicus** [comment]
You might want to beta-test this (not published to master yet):
https://github.com/Stadicus/guides/blob/lncli-web/raspibolt/raspibolt_69_lncli-web.md
