### ISSUE TITLE
Should bitcoin.conf in /home/admin be owned by root?

### ISSUE THREAD

**Issue by nipponese** [Stadicus/guides#93]
In [Bitcoin -> Autostart bitcoind](https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_30_bitcoin.md) there is a command that copies `/home/bitcoin/.bitcoin/bitcoin.conf` to `/home/admin/.bitcoin`:
```
$ sudo cp /home/bitcoin/.bitcoin/bitcoin.conf /home/admin/.bitcoin/
```
This sets the owner as `root`. Shouldn't the owner of this file actually be `admin`?

**Comment by Stadicus** [comment]
You're right, the file is owned by root. This is ok, however, as it is only needed by `bitcoin-cli` to retrieve the rpcpassword. User admin has read access, so that works.
