### ISSUE TITLE
couldn't connect to server: unknown (code -1)

### ISSUE THREAD

**Issue by johneakin** [Stadicus/guides#96]
Instead of 'admin' user I am just using 'pi'
Bitcoin debug.log is currently showing sync'ing the blocks (Progress 0.26)

However when I run:
/home/bitcoin/.bitcoin $ bitcoin-cli getblockchaininfo
error: couldn't connect to server: unknown (code -1)

This step is completed (changed admin to pi):

#Copy bitcoin.conf to user "admin" home directory for RPC credentials
$ mkdir /home/pi/.bitcoin
$ sudo cp /home/bitcoin/.bitcoin/bitcoin.conf /home/pi/.bitcoin/

Do I have to wait for sync'ing to complete before the bitcoin-cli getblockchaininfo works?

**Comment by nipponese** [comment]
No, but it sounds like the daemon isn't running. What happens when you run `sudo systemctl status bitcoind.service`? Do you see `Active: active (running)` or something else?

**Comment by johneakin** [comment]
$ sudo systemctl status bitcoind.service
● bitcoind.service - Bitcoin daemon
   Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled)
   Active: active (running) since Wed 2018-06-27 10:00:58 BST; 23h ago
 Main PID: 703 (bitcoind)
   CGroup: /system.slice/bitcoind.service
           └─703 /usr/local/bin/bitcoind -daemon -conf=/home/bitcoin/.bitcoin...

Jun 27 10:00:56 systemd[1]: Starting Bitcoin daemon...
Jun 27 10:00:58 systemd[1]: Started Bitcoin daemon.

**Comment by johneakin** [comment]
If I stop & start the service manually it works
sudo systemctl stop bitcoind.service
sudo systemctl start bitcoind.service

But if I reboot the pi, even though the service is running i get the error:
error: couldn't connect to server: unknown (code -1)

Any idea?

**Comment by nipponese** [comment]
Re: this section [Autostart bitcoind](https://github.com/Stadicus/guides/blob/master/raspibolt/raspibolt_30_bitcoin.md#autostart-bitcoind), did you create the service as the `admin` user or the `bitcoin` user?

**Comment by nipponese** [comment]
I had a similar problem, and even though the problem went away, I never felt I 100% understood the cause. Ultimately, I don't think it matters unless you actually do want to use bitcoin-cli commands.

Try `sudo tail -f /home/bitcoin/.bitcoin/testnet3/debug.log` and you can see if the testnet chain is syncing or not. Look for the `progress=` label. A value of `1` means it's 100% synced.

**Comment by Stadicus** [comment]
Does `bitcoin-cli` work for the user **bitcoin** without issues? You can check by opening a sub-session with that user: `sudo su bitcoin` (`exit` brings you back to the previous session).

If so, it might be an ownership issue of the `bitcoin.conf` file in the pi user home.

Try the following (use **pi** instead of **admin**)
```
$ sudo chown admin:admin /home/admin/.bitcoin/bitcoin.conf
$ sudo chmod 600 /home/admin/.bitcoin/bitcoin.conf
$ ls /home/admin/.bitcoin/
```
This should set the owner and access rights of the file `bitcoin.conf` as follows
```
-rw-------  1 admin admin  469 Jun 22 19:37 bitcoin.conf
```

Let me know if this helps

**Comment by johneakin** [comment]
Changing the permissions seems to have fixed it.
Thanks
